# 数据库连接池配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 1
  jackson:
    # 你添加的时间字符串转为yyyy-MM-dd格式的date;返回前端的时候转为yyyy-MM-dd格式的字符串
    date-format: yyyy-MM-dd
    time-zone: GMT+8

# mp配置
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

# 不需要权限校验的请求
auth:
  ignoreUrls:
    - /manager/login
    - /manager/login2